CREATE TABLE `kyc_forms` (
	`id` integer PRIMARY KEY NOT NULL,
	`account_type` text NOT NULL,
	`account_sub_type` text,
	`email_address` text NOT NULL,
	`phone_number` text NOT NULL,
	`street_address` text NOT NULL,
	`city` text NOT NULL,
	`state` text,
	`postal_code` text NOT NULL,
	`given_name` text NOT NULL,
	`family_name` text NOT NULL,
	`middle_name` text,
	`date_of_birth` text NOT NULL,
	`tax_id` text,
	`tax_id_type` text NOT NULL,
	`country_of_citizenship` text,
	`country_of_birth` text,
	`country_of_tax_residence` text NOT NULL,
	`funding_source` text NOT NULL,
	`employment_status` text NOT NULL,
	`employer_name` text,
	`is_control_person` integer NOT NULL,
	`is_politically_exposed` integer NOT NULL,
	`immediate_family_exposed` integer NOT NULL,
	`document_type` text NOT NULL,
	`document_number` text NOT NULL,
	`document_file_link` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
